---
version: 2.1
jobs:
  build:
    docker:
      - image: debian:9.8
    steps:
      - checkout
      - run: apt update
      - run: apt install -y curl libssl-dev libtinfo-dev
      - run: curl -sSL https://get.haskellstack.org/ | sh

      - restore_cache:
          keys:
            - v1-stack-{{ checksum "package.yaml" }}
            - v1-stack-

      - run: stack setup
      - run: mkdir ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: stack build --only-dependencies --test -j1
      - run: stack build --test --no-run-tests

      - save_cache:
          key: v1-stack-{{ checksum "package.yaml" }}
          paths:
            - .stack-work
            - /root/.stack

      - run: stack test

      - run: |
          if [[ "$CIRCLE_BRANCH" == master ]]; then
            ssh-keyscan -H demo.getgig.org >> ~/.ssh/known_hosts
            stack install hapistrano
            stack exec -- hap -c deploy/staging.yaml deploy
          fi
