---
nginx_vhosts:
  - listen: "80"
    server_name: demo.getgig.org
    return: 301 https://$server_name$request_uri
    filename: demo.getgig.org.80.conf

  - listen: "443"
    server_name: demo.getgig.org
    extra_parameters: |
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:3000;
      }

      ssl on;
      ssl_certificate /etc/letsencrypt/live/demo.getgig.org/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/demo.getgig.org/privkey.pem;
